version: "3.3"
services:
  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  redistimeseries:
    image: redislabs/redistimeseries
    container_name: "redistimeseries"
    ports:
      - "6380:6379"
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "3000:3000"
  tracker:
    build: ./tracking
    container_name: "tracker"
    command: bash -c "python tracker.py mmtracking/configs/mot/deepsort/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py --redis redis://redis:6379"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      redis:
        condition: service_healthy
  producer:
    build: .
    container_name: "producer"
    ports:
      - "5002:5001"
    command: bash -c "python3 producer.py --verbose True -u redis://redis:6379 data/race.mp4 & python3 server.py -u redis://redis:6379"
    depends_on:
      redis:
        condition: service_healthy
